/**
 * Config and plan for a plain AWS server in the user's own AWS account.
 *
 * Every default comes from the template registry rather than from this file, so
 * the registry stays the only place that decides what a deployment is allowed to
 * cost. Validation rejects out-of-range values instead of clamping them: a user
 * who asked for a 500 GB disk should be told no, not quietly given 100 GB.
 *
 * This runs at plan time, before any row exists. The authoritative gate is still
 * validateTerraformVariables in the run driver, which re-checks all of this
 * against the registry plus the template's `available` flag.
 */

import type { DeploymentStatus } from "../../db/generated/client"
import { TEMPLATES } from "../terraform/terraformTemplateRegistry"
import { safeProjectName } from "../terraform/terraformVariableValidator"

export const AWS_SERVER_TEMPLATE = "aws-ubuntu-server"

const TEMPLATE = TEMPLATES[AWS_SERVER_TEMPLATE]

export type AwsServerConfigInput = {
  projectName?: string | null
  region?: string | null
  instanceType?: string | null
  volumeSizeGb?: number | null
}

export type AwsServerConfig = {
  projectName: string
  region: string
  instanceType: string
  volumeSizeGb: number
}

export type PlanLine = { label: string; value: string }

/** Real hardware per allowed instance type. Every t3 size is 2 vCPU. */
const INSTANCE_SPECS: Record<string, string> = {
  "t3.micro": "2 vCPU, 1 GB RAM",
  "t3.small": "2 vCPU, 2 GB RAM",
  "t3.medium": "2 vCPU, 4 GB RAM",
}

/** What the UI may offer. Mirrors the registry so the form cannot widen it. */
export function awsServerOptions() {
  return {
    template: AWS_SERVER_TEMPLATE,
    label: TEMPLATE.label,
    description: TEMPLATE.description,
    regions: TEMPLATE.allowedRegions,
    instanceTypes: TEMPLATE.allowedInstanceTypes.map((type) => ({
      type,
      specs: INSTANCE_SPECS[type] ?? "",
    })),
    defaultInstanceType: TEMPLATE.defaultInstanceType,
    volumeSizeGb: TEMPLATE.volumeSizeGb,
  }
}

export function validateAwsServerConfig(input: AwsServerConfigInput):
  | { ok: true; config: AwsServerConfig }
  | { ok: false; error: string } {
  const projectName = safeProjectName(input.projectName || "")
  if (projectName.length < 3) {
    return {
      ok: false,
      error:
        "Server name must be at least 3 characters, using letters, numbers and dashes.",
    }
  }

  const region = input.region?.trim() || TEMPLATE.allowedRegions[0]
  if (!TEMPLATE.allowedRegions.includes(region)) {
    return {
      ok: false,
      error: `Region ${region} is not available for this template. Choose one of: ${TEMPLATE.allowedRegions.join(", ")}.`,
    }
  }

  const instanceType = input.instanceType?.trim() || TEMPLATE.defaultInstanceType
  if (!TEMPLATE.allowedInstanceTypes.includes(instanceType)) {
    return {
      ok: false,
      error: `Instance type ${instanceType} is not available for this template. Choose one of: ${TEMPLATE.allowedInstanceTypes.join(", ")}.`,
    }
  }

  const { min, max, default: fallback } = TEMPLATE.volumeSizeGb
  const volumeSizeGb = input.volumeSizeGb ?? fallback
  if (!Number.isInteger(volumeSizeGb) || volumeSizeGb < min || volumeSizeGb > max) {
    return {
      ok: false,
      error: `Disk size must be a whole number of GB between ${min} and ${max}.`,
    }
  }

  return { ok: true, config: { projectName, region, instanceType, volumeSizeGb } }
}

/**
 * The plan a user approves. Derived entirely from the validated config and the
 * fixed Terraform module, so what is listed here is what Terraform creates.
 */
export function awsServerPlan(config: AwsServerConfig): PlanLine[] {
  return [
    { label: "Template", value: TEMPLATE.label },
    { label: "Provider", value: "Your own AWS account (EC2)" },
    { label: "Server name", value: config.projectName },
    { label: "Region", value: config.region },
    {
      label: "Instance",
      value: INSTANCE_SPECS[config.instanceType]
        ? `${config.instanceType} — ${INSTANCE_SPECS[config.instanceType]}`
        : config.instanceType,
    },
    { label: "Disk", value: `${config.volumeSizeGb} GB encrypted gp3 root volume` },
    { label: "OS", value: "Ubuntu 24.04 LTS" },
    { label: "Network", value: "Default VPC, public subnet, static Elastic IP" },
    { label: "Open ports", value: "80 and 443 from anywhere" },
    { label: "SSH", value: "Port 22, restricted to the TisiOps worker address" },
    { label: "SSH key", value: "Generated by TisiOps, stored encrypted" },
    { label: "Terraform module", value: TEMPLATE.modulePath },
    { label: "Billing", value: "Charged to your AWS account, not to TisiOps" },
    {
      label: "Retry",
      value: "Reuses Terraform state, so a retry never creates a second server",
    },
    { label: "Removal", value: "terraform destroy" },
  ]
}

/**
 * The timeline the progress screen draws for a plain server.
 *
 * Shorter than the n8n one because less happens: no application to install, no
 * DNS, no SSL. Showing steps that will never run reads as a stall. Lives here
 * with the plan rather than beside the database code so it can be checked
 * without a connection.
 */
export const AWS_SERVER_STEPS: { status: DeploymentStatus; label: string }[] = [
  { status: "PENDING", label: "Deployment job created" },
  { status: "QUEUED", label: "Waiting for a worker" },
  { status: "RUNNING", label: "Worker picked up the job" },
  { status: "PROVISIONING_INFRA", label: "Creating the EC2 instance" },
  { status: "HEALTH_CHECKING", label: "Verifying the server" },
  { status: "LIVE", label: "Server is ready" },
]
